services:
  deps:
    image: node
    volumes:
      - ".:/app"
    working_dir: /app
    command:
      - sh
      - -c
      - yarn
    profiles:
      - run
  app:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    working_dir: /app
    command:
      - yarn
      - run
      - dev
volumes:
  data: null
  node_modules: null
