# Tech Debt: Create separate GCP dev/prod deploys with auth
name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_IMDS_PARSER_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy imdsparser-dev --region us-central1 --source .
        env:
          GCP_SA_KEY: ${{ secrets.GCP_IMDS_PARSER_SA_KEY }}
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
