name: "Surface: Check PR"

on:
  pull_request:
    branches:
      - dev
      - prod

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: surface
        run: yarn install

      - name: Check linting
        working-directory: surface
        run: yarn run lint:check
